### ISSUE TITLE
this sucks

### ISSUE THREAD

**Issue by ghost** [dotpcap/sharppcap#360]
no!

**Comment by chmorgan** [comment]
Upset that you aren't as clandestine now that your network traffic is being parsed by sharppcap?

**Comment by clandestinenetworks** [comment]
hahahaha sorry I actually ended up just continuing to work with pyshark just because the header / layer decoding is a little farther along. I actually would prefer though working with .NET especially there were more decoders like with scapy. I ended up even with pyshark having to write some pretty remedial code to do naive deduplication using a chunked reader but it worked out and its really fast. Still its no substitute for C# though

**Comment by chmorgan** [comment]
Hah, I’m glad you got things working.

What kinds of decoders? These are open source projects so we run on
suggestions and proposed code changes.

Chris
